### ISSUE TITLE
Enable logging on launch

### ISSUE THREAD

**Issue by GabLeRoux** [yrammos/SublimeLog#1]
Hey there, I'm trying to find which plugin makes my Sublime taking way to long to open (around 30 seconds). I tried to check at the logs, but it seems I have to activate this plugin before it starts logging output. I removed all the plugins that were adding tracelogs in Sublime console, but still I can only access logs and console once sublime is opened and there is no timestamp on each lines of the console.

ReadMe says

> The log is erased and recreated each time Sublime Text is launched.

Doesn't seem to start each time I open Sublime. Any idea on how I could make sure this is triggered on Sublime Launch so I don't have to do some sort of dichotomic search for the single plugin that cause sublime to take so long to start? (Note, it's not this plugin, installed it after it was too long to start) ;)

Atom has a some cool plugins for this with builtin profiler, but 2gb file limitation was a blocker for me.

**Comment by yrammos** [comment]
Please allow me a couple of days to investigate and I'll get back to you. Thanks.

**Comment by yrammos** [comment]
Well, I find a conceptual obstacle to this. As far as I know, there is no way to control the order in which SublimeText bootstraps its packages on startup—and I don't even know whether that order is, for all intents and purposes, "deterministic". Automatically enabling SublimeLog "on startup" could therefore create the misleading expectation that all console output will be captured, right from the moment the console itself becomes active. That is what the expression "on startup" seems to suggest, after all… In your case, for example, there would be no guarantee that such a feature would actually help you track the culprit down, because there is no way of ensuring (AFAIK) that SublimeLog would be loaded before that culprit.  So I am reluctant to add a feature that seems doomed to work inconsistently. Let me mull this over for a little while—perhaps there is a SublimeText API for prioritizing plugin loading? Ideas welcome.

**Comment by GabLeRoux** [comment]
Hey thanks for your time, I don't know much about sublime's api. If it's impossible, don't loose too much time on this ;) 

There's a small section about "Plugin Lifecycle" in https://www.sublimetext.com/docs/3/api_reference.html

But doesn't talk a lot about `plugin_loaded()`.

**Comment by yrammos** [comment]
Yes, I am afraid the SublimeText API does not allow for such low-level tweaking. Atom is much more customizable and modular in that sense. Sorry for not being able to provide a solution. Perhaps you could try to manually identify which plugin tends to load first in your setup, and insert a one-liner in its source code to show the console (something like  `sublime.active_window().run_command('showPanel console')`, for example).

**Comment by Kristinita** [comment]
+1.

@yrammos, may be [**this answer**](https://github.com/scholer/sublime_logging_control/issues/2#issuecomment-195458740) of Sublime Text developer help you.

But I will be glad, if SublimeLog will be write console log even without first Sublime Text messages. It is bad activate SublimeLog manually.

Thanks.

**Comment by yrammos** [comment]
To my knowledge, there is no reliable and well-behaved way to control the order in which plugins are loaded, so my response above, dated 2015-06-15, still applies. Sorry about this.

**Comment by Kristinita** [comment]
@yrammos , if SublimeLog even do not logged plugins loading, but will be start automatically, it would be nice.

Thanks.

**Comment by yrammos** [comment]
Thanks, @Kristinita. For lack of time these days, I cannot promise this otherwise simple tweak. But will keep it in mind.
